### ISSUE TITLE
something - ia003

### ISSUE THREAD

**Issue by tsingyu42** [MaiYunfei2000/hello-world#2]
# 从比特到上帝

## 目录

- 随想
- 追忆
	- 引子
	- 挖坑
	- 入坑
	- 停滞与迷茫
	- 伦敦的天气
	- 飞出丛林
- 小结
	- 感谢
	- 成长
	- 不足与反思
- 尾声
- changelog

### *1*

时间，在我四周飞快地转圈。

扎入信息之海的我，环视着亦此亦彼的混乱纠缠地飘荡过的气泡流，它们透镜般地将时光复杂折射。这里是斑斓而灰白的海，这里是万华镜。在我这里，时间是沸腾的。

### *2*

我的不安与焦虑已经临界了好久。内在的、意识的高熵运动仿佛要将我的脑壳冲破。

升维！输出！我对自己怒吼。

### 引子

这次来开智的直接原因是想解决自己的遇到的难题。经历了高二高三，我终于决定了要往认知科学方向前进，不过这才解决了第一步。虽然离大二选导师还有一段时间，但我必须尽快选定自己下段旅途的具体方向。初步选中的老师都专长于认知神经科学或计算认知科学，可这些学科究竟是些什么呢？

我需要尽快给自己一份答卷。我已经没多少时间了，无比宝贵的年轻时光、学生时光就只有这么短短几年，荒废几天，就荒废了几年、十几年。不能再犹豫徘徊了，不能靠自己一个人胡乱地摸索了。

我终于鼓起勇气把信任向外托付。被高考拖了一年多，这回终于可以正式加入开智这个学习共同体。于是一入开智深似海。

### 挖坑

刚入开智，就注意到了结业项目，虽然还几乎不了解这是什么，但感觉似乎很重要。于是当机立断给自己挖出一个大坑：在讨论区发帖寻求结业作业的伙伴，方向是认知神经科学或计算认知科学。于是早在第一周，我，刘旭，王婧靖，我们的认知科学小队就组好了。

### 入坑

某个星期五，阳老师在群上灌水安利计算认知科学。我心想，这不就有个时间源头吗。向内看，我与计算机有一段绵长爱恨情仇，向外看，国内似乎还没很多学者在专门做这个领域的研究，这个领域研究起来成本低、迭代快。我才刚离开起点，成长空间很大，如果利用国内外时间差来套利，自己或许就能成为时间源头。

阳老师说，用十二年时间掌握四种技能。那么我在三十岁前这十二年的第一个三年，就给自己锻造这么一把重剑吧。

终于定好了，计算认知科学。义无反顾地跳进自己挖的大坑。

### 停滞与迷茫

理想很丰满，现实很骨感。我，小白。我，战五渣。学完了几周课程，我发现我脑海中的问号更加密密麻麻了。我对于结业作业怎么进展仍然毫无头绪。

临近跨年，迷迷糊糊地初次摸索GitHub的使用，建了一个仓库。然后去维基和阳老师博客挖了一批线索，逼自己写了一份模棱两可的项目idea。本打算元旦（w4d2）展开第一次小组会议，定好了时间却因为突发乌龙而启动失败。

随后一周（4w），项目的推进被搁置了。然后（5w）期末考来了，我不得不把开智的事情放在一旁。

然而即便是期末考期间，我也在考虑着BP的事情，并在晚睡前抽几分钟看一下微信和GitHub。果然，因为我没有设立一个清晰的框架，没有明确组员们的工作，所以哪怕是信息分析第一阶段的信息获取，除了元旦假期大家各自发在GitHub上的一点点内容，并没有新的进展。于是在BP和期末考的双重压力下，不免非常焦虑和压抑。有时会抱怨自己，明明是第一次来开智上课，不熟悉课程和结业项目，自己又那么年少无知，没有足够强的能力组织好队伍、没有好好掌握每周学的内容，就这么急忙开坑，把别人拉下水。然后时不时会想，自己这么早就来参加本来是针对24~36岁人士的开智课程，越级挑战这些如此高难度的事情，真的不是无谓作死吗。

消极有什么用，还不如好好想想怎样改变当前的局面。

同学和教练们都提及要收束作业的体量，把项目切割。于是就反思自己原本的项目idea，我试图做一个比较完整的全局认识，这样工作量太大，而我们三个人都很忙碌，这不现实。于是得切割切割再切割。两周期末考之间的周末夹缝，我抽出几个小时斩钉截铁地想出一个idea2.0，然后喊组员开会。这次大家终于同时有空了，周五（5wd5）小组开成了第一次会议。大家明确了各自的可支配时间，我要到6wd3下午考完试以后才有空开展工作，刘旭同学则突遇其它要忙的事情只能每晚抽点时间参与，王婧靖同学则相对有空。于是王婧靖同学成为消化学术内容的主力。我们瓜分了阳老师推荐的计算认知科学剑桥手册里提到的五个流派，我领走贝叶斯，刘旭领走ACT-R，其它三章交给了王婧靖同学。除此之外，我还负责收集学者和机构的信息并整理出一份信息清单，以及整合大家的信息制作PPT并演讲。信息分析的框架当然是很清晰了，时空变量，可是报告具体该怎么做还是缺少头绪。我说现在干想也没用，先行动，整理输出一些信息才能有下一步想法，下周（6w）再说吧。

### 伦敦的天气

赶BP的最后几天，我的心情变化非常厉害，项目有头绪能继续进展时就非常积极乐观，进展阻滞时又变得很焦虑、压抑。每天起起落落，像坐过山车，又像伦敦那频繁变化的天气。

#### *1*

最后一周的周三（6wd3）上午，我终于考完了让人脑扁的期末考。本想终于可以顺畅地推进项目了，打算先啃下学术内容消化这一块大骨头。周四的时候，绝望的情绪蔓延至我的身体各处。英文或许四级，数学尚只学了半个高数，心理或认知科学也几乎没学些什么的我，始终看不懂这本剑桥手册，反复撞墙碰壁。

及时止损吧，先做别的容易事情，变量关系或者说最小话语体系，最后再解决。我补看上周四（5wd4）的阳老师答疑，继续细化后续思路。

「空间」，什么是不变的，或是变化很小很慢的？阳老师已多次提醒我们。人、机构，此外还有容易忽略的，「学术流派」或「学术源头脉络」这一已沉淀在历史中、印刻在历史中这一永垂不朽的恒定事物。

因为已在网络空间中已经穿梭十余年，多少对各种各样的信息链节很敏感，于是周四周五挖掘并整理出一份学者和机构的信息清单。虽然这个工作对我来说难度并不大，但是不得不说它是繁重的。但正是因为这种「必要难度」，在编码、存储端增加难度，我才很快的从一天前对计算认知科学还毫不怎么了解的懵逼状态，转变到一天后若是问起计算认知各大流派的学者机构分布以及学者与学者、学者与机构的网络关系时可以稍微侃侃而谈的程度，计算认知科学的空间全局已经通过这种工作初步烙印在脑中。

那么「时间」呢？我又犯难了。在这一块我不得不踏出舒适区了。

#### *2*

周五，离Deadline越来越近，我的项目除了一份清单，再没有别的进展。

我尝试做一下PPT的框架，先把思路铺开，卡住了。又思考怎么解决做出时间和变量关系，也卡住了。然后就在两个环节间来回切换转圈。不知不觉间白天快过完了。我的心又悬了起来。

隔壁的战略小组一直很活跃。仁冲教练提到“Deadline是第一生产力”、“2期我第一个讲的，然后开讲之前5分钟都还在写PPT”，然后他们组就第一个去讨论区报名帖那儿报道了。我想，用ddl倒逼自己发力好了。于是跟在后面报了第二个上。

这个晚上开了第二次也是最后一次会，明确路演事宜、接下来的分工并碰撞了一下想法。

至于「时间维度」，不知什么时候以及为什么，心中的阴云又散开了，似乎有了点眉目。在时间、精力、能力均有限制的条件下，我还可以继续偷懒，用小得多的成本在一个相当短的时间内取得一个「近似的近似的最小全局」。

#### *3*

周六周日仍然处于卡顿的状态。我陷入了一个死循环：希望做出一部分PPT来，但尚没有可以填充的内容，有待自己和组员输出卡片；希望写出一些卡片，但需要一个清晰的PPT思路框架。

另外一个卡住我们组的地方是通俗与有趣度，周六下午晚上终于翻了下刚到货的《算法之美》，里面有很多有趣的东西，但不知与我们的BP内容有什么共通点。

我原本的一些不成熟的PPT思路被刘旭同学指出不靠谱需要推掉，以及，我被强建议要用keynote来做幻灯。没用过keynote的我花了一点力气克服了一下自己的畏难情绪果断丢掉WPS重头再来，适应了一下keynote并研究一下怎么利用好刘旭同学给过来的模板。消化完刘旭和王婧靖同学输出的卡片和找到的一些关键文章，周日也过了一大半。

我又回头去琢磨怎么理出贝叶斯流派的时间维度。于是实践了一下周五模糊想出的思路。假如一篇论文是贝叶斯的里程碑，它的标题应该会有个「bayesian」吧？我发现从约书亚（Joshua）的主页批量下载的论文不全，以及许多论文PDF抓取不到元数据，索性抛开zotero，直接回到谷歌的学者profile，command+F用keyword「bayesian」页面内查找，一个个论文摘要地看，最后确认了他1999年的博士论文就是贝叶斯流派诞生的里程碑。在这个过程还伴随着验证：如果约书亚这一篇贝叶斯论文不是里程碑的论文，那么它一定是基于他更早的贝叶斯论文提出来的，体现在文中，就是：①摘要、引言或结尾总结部分，“在xxxx中，我提出/提到xxxxxxxx”之类的话语（语言表达不局限在这种，但意思很好把握）。②文末的参考文献中会列出他自己写的更早的论文。

我作为一个英语还偏弱的学渣，读一篇篇文章是读不下去了，但抽出一个个段落，配合谷歌翻译，总能读得下去吧？这是我的偷懒方法。随后用相同方法get到了格雷戈动力系统流派的历史里程碑。

于是对于自己这个寻找「时间」维度信息的策略，其实还是与开智卡包里教的相似，不过更加偷懒了，我管它叫「抽样-跳跃」。但是它的弊端是很明显的，仅依赖较少信息就，很需要补上交叉验证。因此在时限拉大的情况下，还是千篇一律论文摘要+结构阅读百篇论文最靠谱又高效。

#### *4*

周日晚上，幻灯制作继续卡顿。我仔细一梳理，发现是因为缺乏几张关键的流派卡片，只要这些卡片一出来，就能把所有内容整合成一条报告思路了。于是九点多我先小睡一下，等

睡醒的我原以为终于万事俱备，只欠幻灯。结果凌晨时和刘旭同学因为报告内容的意见不一致又卡了一段时间，我认为只需要介绍计算认知科学本身的历史脉络就可以了，不需要在开头背景部分花功夫多介绍一条认知科学的历史脉络。最后我发现是我在无谓地钻牛角尖，因为内心已经开始有些消极退缩，进而抗拒消化新的信息。

#### *5*

终于可以把幻灯做下去了。本着只制作优质作品的自我要求，幻灯的任意一个细节包括文字内容、文本格式、图标、图形，这些元素如何良好配合以实现更好的呈现效果，都经过了仔细考虑。于是我在ddl压迫下，既尽快又慢吞吞地，清晨正式开始赶制幻灯，一路做到傍晚。我的幻灯除去两天前捣鼓得很烂被否掉的几张PPT，转战keynote重头再来之后就只做出了一个版本——初版就是终版——并且直到路演前15分钟才写完讲稿。然后没有再次审视、修改以及预演的机会，就拿出来呈现了。

刚做完报告没有多少间歇就得去路演了，我的内心悬得很紧。加上开头出现的共享屏幕乌龙，更是让我路演过程中紧张到快要爆炸。底气的缺乏和昏沉的大脑则让我在演讲时越念越沮丧，中途有几次意识险些断线。不过还用最后一丝气力撑着自己完成了路演。随后，我这个落到谷底的皮球反弹了回去。

### 飞出丛林

这一个半月的信息分析之旅，大脑一直在全力运转，CPU和内存始终占用百分百，感觉身体被掏空。

伴随着BP的完成，突然恍然大悟。

终于体会到阳老师的意思了。可不是么，最小全局认识是一览众山小，是登泰山而小天下。

掌握一手的信息，有了一手的认识，我直接飞出了层叠的丛林。高校本科的阻滞没法割我韭菜了，我主宰我的认识与行动，不再被迫盲目、无措地依赖他人。

## 小结

我这个年少无知的小小白第一次来开智就当队长带出了一个BP！（内心稍稍膨胀一秒钟~）

虽然心态时起时落，但是总体上越做越有感觉，之前很多模棱两可的知识都逐渐清晰，特别是做完幻灯之后，Boom！

#### 感谢我的组员

非常感谢王婧靖同学和刘旭同学，他们深挖、消化学术材料，成为了我坚实的后盾。他们的学术功底成为了我输出结业报告的保障。有疑惑或是理解、表述上的错误，可以及时跟他们碰撞，加深理解或修正错误。光有我的广度搜索、快速铺展，没有他们帮助保证的细节正确，我也就是一个招摇过市的江湖混混。刘旭同学还贡献了很多关键的帮助，例如提供优质keynote模板和一些关键的文献，在我陷入牛角尖的时候批评我，把我拉回来（当然，我也会切割刘旭同学的想法和输出卡片，减少知识的诅咒以及约束BP体量。我们俩会时不时相互碰撞）。

张美凤同学周四晚上在群上寻求组队，就吸收进来了，但尚刚开始学习课程卡包。于是分担一些难度相对低的工作，例如整理学者头像拿来做PPT、了解一下学者文献的社会引用情况，以及交叉验证学者的信息。这也帮我们节省了一些时间。

#### 感谢开智的大家

如果没有阳老师、课程组、教练们创建一个这么优质的学习空间，如果没有那么多优秀到爆炸的同学，我的快速成长也无从实现。

#### 以及

当然也要感谢，果断决定不再观望而是尽快来开智学堂的我，一路遇到那么多困难仍然坚持下来的我。

#### 耐虐值+1

这一个半月的时间，大脑一直在全力运转，CPU和内存始终占用百分百，感觉身体被掏空。从周三（w6d3）开始，每天都是一点多睡觉。到了最后关头，周日晚上小睡了两三小时，周一则一直没睡觉。自己又久违地爆了一回肝，虐了一回脑。

现在回想过来，大概是这些因素让我每次经历困顿时都咬牙挺过。

第一个自然是同侪压力。前几周学卡片完成作业时的感觉还是不明显，因为知道我和其他大部分同学年龄差距还是挺大的，所以看着他们一个个都多么牛逼时自己仍然很难产生压迫感。但直到最后两周，看着观察的战略小组和虚拟现实小组一直在有效推进，我就会不断有压力，想着“不行啊必须有所行动不然就真的会凉啊”等等；给我打击更大的是，回看5w的结业交流时，从胡丽同学的分享中得知二期同为大一的Alex同学也当着结业项目的队长，并且把团队带领得很好，合作有序，然后再看看自己那混乱的GitHub仓库，看着自己未能协调好的工作，羞耻感顿时生发出来。这回真的是同侪的压力了。原来这就是所谓的被动进步。

第二个是作为队长的责任。路演介绍小组时，我介绍自己说我是打杂的，这当然是调侃，我必须得明确自己的工作。我要协调好各人的工作，以及是负责[理解消化、整合各路信息并提炼出一份报告]的中枢。我把其他同学拉进了这个坑，必须有个交待。想到自己身负重担，我就不敢持续懈怠下去。

第三个是阳老师说的“年轻时从困难的事情入手”，趁年轻多做难事。自己已经选择了一条很陡很陡的曲线了，这是一条不归路，唯有前进。于是经常拿阳老师的各种金品鸡汤来给自己打气。

第四个是自己在群上和讨论区适度活跃，让大家知道自己的存在。于是自己就会意识到，有人在看着呢，你敢凉拌？你敢咸鱼？

#### 最大的收获

学术信息分析和组队完成BP的框架。

以后从一个学科过渡到一批学科，从一个BP到一批BP，自己会完成得越来越好，能力也会越来强。

#### 共享屏幕之坑

在预路演时幻灯是良好播放的，可正式路演时却出了乌龙。我后来才发现是keynote的锅。打开了keynote的云协作，它就会禁止文件以任何形式从非iCloud的途径传出，其中包括上传文件和共享屏幕。那么继续追及原因，锅在我身上。在路演时间，我应该把keynote文件丢给组员，而不是开启iCloud云协作。

以及下次路演时，无论预路演情形如何，都得假定自己会GG，正式路演开头几秒先简单切下幻灯问下观众是否正常。怕剧透的话就在开头插两页无实意但有简单变化（例如，“test1”、“test2”）的幻灯，专门拿来测试用。

#### 有趣度

这次未能从计算认知科学中挖掘出一些有趣的东西，是这次项目失败的地方。

目前对于如何有效挖出有趣点，仍然没有很多头绪。这个只能之后继续努力了，以及希望有心得的同学们开源一下idea呗。

#### 团队协作

这次纵然成功完成了结业路演，但是作为队长我还是有很多不合格的地方。

GitHub协作很凌乱。

- 前期很长一段时间因为各种主客观原因并没有什么进展，收集的东西很零碎，难以用上。
- 最后我在做幻灯时还是手忙脚乱，并且需要去code、issues、微信群上翻找用于做报告的卡片。在这里花费的心力是很亏的。

复盘以及学习其他小组的写作协作情况之后得出，这些都是我这位队长的失职。开头一定要自己先带头上阵，丢出一个明确具体的框架，并示范每处内容到底怎么制作、提交，随后大家才好开展自己的工作。我这次虽然出了思路、框架、协议，但是它们很多都是无实效的，没有匹配上具体情况，模棱两可。

另外，有一些细节问题应该放到GitHub发issue异步沟通而不是放在微信群，这样容易陷入细节的泥沼而影响大局。

Todo：

- 继续仔细学习其它小组的合作细节。
- 学习wiki的搭建，并假定自己重做一次项目，思考该如何搭建GitHub的readme和wiki。

#### 时间浪费

阳老师在第二周答疑时提过，我们经常遇到的问题大多可以分为两类，一是技术问题，二是心态问题。我自己这几周反复亲验了这个观点。无论是之前完成进阶作业，还是这次做结业BP，我有好多时候都在与自己的畏难情绪做斗争。这次虽然完成BP的时间很短，但是其中仍有相当一部分时间耗在了内心斗争上。我的内心似乎分成了两部分，一边是窝在原地死活不肯动的猪或牛或象或者各种你能想到的动物，另一边则是无比焦急的驯兽人。

一点点把我拉着往前走的，是前文提及的种种。然而仅凭这些仍然很难根治这种问题。下一次做信息分析时我已经后知后觉地知道该怎么走了，自然不会再犹豫、犯难、踌躇不前。可我再次越界，进入一个新的学习深水区，又接触高密度的苦难事物时，这个认知难度和畏难情绪捆绑在一起的强力组合杀又会把我给困住一段时间。

所以我该怎么破解呢？

想法一：继续多被虐，虐多了就习惯了，虐多了就没情绪了。额，那，继续加油吧。

想法二：情绪管理。书单走起！可惜接下来的一段日程已经排满了……

想法三：HACK开智学习的框架。这类似想法一，需要经历重复的模式。额，那，今年继续上课，继续加油吧……

我还得不到确切答案。可否有大侠支招？

## 尾声

阳老师在路演的最后一天说到，完成BP只是开始。我们离实现真正的目标还有相当的距离，休整几天后就得继续上路了。

另外，下次在信分四期或五期或者其它课程，就不当坑队友的组长啦。我也学习一下如何当组员，这样才能知道一个团队如何更好地运作。

至于标题是个什么鬼？只可意会不可言传。我也不清楚它到底是个什么意思，它还在我的内隐知识里。

## changelog

190125 1300 麦云飞完成初稿。
190123 0900 麦云飞创建文档。

**Comment by MaiYunfei2000** [comment]
111

**Comment by jining1** [comment]
路演第一天从群里你们的keynote就被震惊了，也给了自己强大的同侪压力。之后自己路演结束以后，看了你们的路演，膜拜。也很想知道你们的信息是如何得出的，看了你的复盘，了解了一些，写的好详细，情景重现和文采点赞！第一次上开智课就能从源头的一手信息里挖掘出时间线、流派，空间线等，太厉害了，学习！深感这样的复盘加上长时间周期会给自己带来的进步，也给我这样的读者学习了很多。如下：
1、可以从重要学者论文的关键语句里挖掘时间线。
> 我又回头去琢磨怎么理出贝叶斯流派的时间维度。于是实践了一下周五模糊想出的思路。假如一篇论文是贝叶斯的里程碑，它的标题应该会有个「bayesian」吧？我发现从约书亚（Joshua）的主页批量下载的论文不全，以及许多论文PDF抓取不到元数据，索性抛开zotero，直接回到谷歌的学者profile，command+F用keyword「bayesian」页面内查找，一个个论文摘要地看，最后确认了他1999年的博士论文就是贝叶斯流派诞生的里程碑。在这个过程还伴随着验证：如果约书亚这一篇贝叶斯论文不是里程碑的论文，那么它一定是基于他更早的贝叶斯论文提出来的，体现在文中，就是：①摘要、引言或结尾总结部分，“在xxxx中，我提出/提到xxxxxxxx”之类的话语（语言表达不局限在这种，但意思很好把握）。②文末的参考文献中会列出他自己写的更早的论文。

这是技术，也是思维习惯。一个打不通，就再想其他办法，要确定自己的最终目的是挖掘时间线。而我忘记了这一点。我在搜集信息时总想着课上讲的实践策略。遇到困难了死磕，或者想着先放着，后面再死磕。总觉得后面还有大片的时间。而不是继续想别的办法。而且自己总想找标准答案，不敢自己得出结论。这是我以后要注意的。
2、在进行内容探索时一直在思考自己的模糊点在哪里，自己想要的是什么，有没有其他办法，会及时止损，这也是我缺乏的认知灵活性，总是被细节卡住，我在理解网络科学的三个高阶模型上花了很多时间，只见树叶，不见森林。在一个坑里进去就很难出来。这是我要思考的问题。
3、搭建好PPT的框架重点找信息，通过卡片的方式输出，这样就降低了最后输出的颗粒度。而我是开演前一天晚上开始做PPT，开演当天写稿子，只能写出大概了，才发现自己有很多信息点没有找，在很多细节的信息点上面卡壳，钻研了很久，因小失大。最后的很多信息点都是临时从综述论文和书上拿的，自己没有像你这样展开自己探索。
4、你的思路引发我思考到底什么是源头。从认知难度来讲，订阅号文章/维基百科/知乎博客等<教材<原始论文，而我平时总是习惯性的从难度最低的入手，这次也是，在这个上面花了很多很多时间，总是不敢啃最难的。而通过原始论文建立全局认识，阳老师讲的千篇一律是一种方法论，我其实并没有很好的内隐。我在使用时就死板的认为一定是先读完再说，忘了读的目的是建立全局认识，这也就导致我不会举一反三，陷入实践策略里不能自拔，没有再回到高阶模型：全局认识和交叉验证。

谢谢分享~

**Comment by tsingyu42** [comment]
后日谈：

> 我才刚离开起点，成长空间很大，如果利用国内外时间差来套利，自己或许就能成为时间源头。

> 掌握一手的信息，有了一手的认识，我直接飞出了层叠的丛林。高校本科的阻滞没法割我韭菜了，我主宰我的认识与行动，不再被迫盲目、无措地依赖他人。

批评：幼稚、肤浅之言。
