### ISSUE TITLE
复盘笔记：190317 2000 《情绪》发布会（Lisa老师部分）

### ISSUE THREAD

**Issue by tsingyu42** [MaiYunfei2000/hello-world#3]
## 复盘笔记：190317 2000 《情绪》发布会（Lisa老师部分）

看完发布会马上凭印象来输出一下~

（PS：我目前只看完了《情绪》的推荐序；刚刚网络有时不幸断开，于是可能漏听一些关键内容。所以下文可能存在看完这本书之后要被打脸的地方）

---

反常识卡&术语卡 情绪建构论

印象

看着直播的时候，我还在想着结束后按幻灯的架构来输出笔记。但后来“啊哈”了一下——哪需要这样一条一条地列出来说呢，只需要从「情绪建构」本身下手就好了！Simple as it is, though, It’s everything! 

一些理论，一些术语，一些反常识，可能还需要初学者花一些功夫去分析归纳分析归纳，但面对「情绪建构论」不需要那么费事，这个词是多么地直白，以至于我们“望文生义”地理解就可以了。（此段话也可以视做多余唠嗑直接砍去，但看在这卡片是生加工物的份上我就暂时不割了）

Lisa老师演讲的主要内容，那几个「反常识」，则是由「情绪建构」——这个TERM本身——演绎出来的二级话语。

你对情绪的既有理解错了——你的表情、言行、生理特征、神经反应通通不是情绪的函数！事实恰恰相反，你把那些元素作为自变量构建出了「情绪」这么一个多元函数。你把那些事物理解成了情绪，然后它们就成为了情绪。从此，“怒目圆睁”被编码为“怒”，“眉开眼笑”被编码为“喜”，“攒眉蹙额”被编码为“愁”……行为亦然。你建立了有关情绪的认知，情绪世界的高楼大厦拔地而起。

```
此卡片只有「印象」，算是对发布会PART1的提取。当然，非要标记出处的话也可以，就是Lisa老师的所有主要研究:D或者可以近似地取《情绪》这本书的整本。

另外，这张卡是即兴演绎出来的，难免少不了演绎不当，或是容易产生歧义的成分，对此希望大家多多交流。当然，我自己也得先扎进《情绪》这本书，验证自己的说法有几分合理。
```

---

题外话

任意卡 （结合上一张卡片以及本文最后一张卡片演绎而出）

脑洞1——既然情绪可以「建构」，那情绪何尝不可以「解构」？

脑洞2——情绪是一种模因！

---

题外话

灌水1

国外普通心理学教材又要大变动了！？？我在比较国内《普通心理学》课本和美国的《心理学与生活》(第19版)时已经汗颜了。而且我的学校用的还是广东高等教育出版社的那本古董一般的《普通心理学》（而且有很多问题，例如《风格感觉》中平克老师举出的很多坏语言特点，那本书疯狂中箭），而不是北师大版的《普通心理学》(第四版)。这差距越来越大了啊……

灌水2

我又对情绪开始逐渐有些感兴趣了……然而已经刚跟了一个认知神经/计算认知科学方向的导师。

这几年还是先专一地搞好第一块领域吧。以后（若是真能变得有点能耐的话）可以学下司马贺，面对万千繁华景象，只取水墨色彩相互渲染之处。

---

题外话

任意卡 我与「情绪」（beta ver.）

我与「情绪」这个topic共舞三次，第一次是小学五六年级，第二次是高二，第三次正在进行。

我在小学五年级时开始关注起「情绪」这个事物。（受制于精力，此处略去千字故事，以后随缘填坑，后同）那时的我，讨厌女孩子般多愁善感的自己，

```
（⚠️未来若成文，改成尾注，后同）PS：“女孩子般多愁善感”可能会被敏感的人拉起一些有关性别的话题，因此同样敏感的我先在此clarify：①我反对这种，以及与此相关的性别刻板印象。②我无法省略“女孩子般”这个定语，因为我成长的环境中已经充斥着各种”男子汉就是要xxxxxxxx，而xxxxxxxx是女孩子才能有的“这种类型的灌输/教导，从家长到幼儿园、小学老师。③如果仅仅是因为“多愁善感”而非“女孩子般多愁善感”，我随后的人生轨迹会大不同。原谅我在此啰嗦解释，这对于我的成长故事来说，是个重要的成分而不宜删去。

我希望此帖仅讨论情绪的话题，而不要被这里带偏了。此帖仅支持情绪相关的话题，不支持性别相关的话题，有意者换个地方异步沟通。
```

于是诞生了一个愿望，希望自己能够像操控电脑一样自如地控制自己的情绪。

六年级寒假的某个片段（2012.01），我立在黑龙江雪乡的林海雪原一角，向视野开阔处眺望。在太阳的呢喃低语之下，世界被上色成银白，时间仿佛被严寒冻结。我的内心先是跪倒于寒冷感，随后被一种圣洁、一种静谧、一种清净包裹了起来。失序的内在不再失序——流液化成雾，雾汇聚成水，水凝结成有序的晶体——意识重获和谐。

若干月后，一个燥热天气，一处没有空调的地方，一个本来就有些心烦意乱的少年快成了要叫出声的烧水壶。

我想冷下来。

无意之举。一幅画面重现在我眼前，我的感觉重新被冰天雪地包裹。我静下来。

我想起了自己的愿望。我觉得似乎可以做些什么了。我抛出一个碎片，将它命名为「冰雪」。后来越来越频繁地，每当浮躁之时，我就会从不存在的空间里拿出它，紧握一下。再后来，又多了一枚碎片，「火焰」。再再后来，我制作了越来越多的碎片。

```
别笑！别笑！憋住！人不中二枉少年orz 那个年纪游戏玩多了、动画漫画小说看多了的男孩子很容易喜欢奇幻/玄幻的东西的吧……什么金木水火土，冰系火系电系，技能道具etc……

另外上面那些文段其实比较含蓄，解读起来会比较费力。
```

（略去一段故事）

转眼间已是高中生。我已习惯于游离在各个圈子之外，默默地观察这个世界。除了头疼于如何好好学习（特别是，记忆到底是怎样运作的(特别是怎么生成牢固的长时记忆)，思维到底是个什么样貌）以及分析自己和他人的理性和非理性行为（特别是后者）以外，青春期的我、与一群青春期少年少女们一同学习生活的我，自然也会连带着关注起自己和他人的「情绪」。

高二xxxxxxxxx（略去一段故事）

我诞生了一个愿望。为了能自如地控制自己，我想尽可能地理性；我想消解掉自己的情绪。

（略去一段故事）

xxxxxxxxxx焦虑xxxxxxxx健康状况xxxxx认知xxxxx工作记忆xxxxx我越来越困惑了：「情绪」到底是个什么？

xxxxxxx

后日谈：我在这个时期的探索活动偏向了错误极端，xxxxx，片面且极端地「解构」自己的情绪，只剩下xxxxx从而影响了我最新几年的轨迹。xxxxxxxxxx。也许我最近才因为一些事情转向了一个新的周期。

我想，我们应该「建构」xxxxxx的情绪，「解构」xxxxxxx的情绪。

---

```
额，太晚了，在此留坑。学生党还有一堆课和差事，反正灵感已经有了。很多很多很多年以后，如果我要以“我与「情绪」”写出一篇自传或小说，目前写下来的内容就是它的框架。但我不承诺会写完。我相当一段时间的重心都不是在这些，而是尽快打好学术基础。
```

今天思考了挺多的。不得不说触动很大。这回又是少有的短时间内突然突然“秒懂”一些东西的情形，第五次了。高中时苦苦思索如何好好学习，花很多时间归纳课本知识，一年如一日地背英语，其中首要子话题之一就是“如何生成牢固的长时记忆”，后来感觉逐渐有了一点点门道但说不出来是什么——于是后来在开智公众号上接触到「必要难度」时“秒懂”了；过去有若干年一直在观察包括自己之内各种事物的发展变化，困惑于各种普遍存在的相互联系又相互干扰的要素，于是接触到政治必修四后“秒懂”了「运动」、「联系」、「矛盾」等等，“原来我之前想的东西名字叫这些！”；小学时困惑自己的思考能力很有限，感觉就像电脑内存一样，内存一满电脑就会卡死，后来在开智公众号上接触到「工作记忆」后“秒懂”；带我走进开智大坑的，在《追时间的人》里接触到的「时空选择论」也是如此。

## changelog

100318 0111 补充脑洞2；完善后日谈。
100318 0036 施工区补充关键词“认知”、“工作记忆”。
190318 0033 补充“今天思考了挺多的”这一段。
190318 0007 文档初稿。

**Comment by alissli** [comment]
一定会有人研究解构吧，2333

**Comment by ViolaChen** [comment]
你总结的不错。。。我来你这里抱走一些文字写反常识卡片

**Comment by ppho99** [comment]
Lisa是个侠女呀！

**Comment by tsingyu42** [comment]
> 讨厌女孩子般多愁善感……

那一段话现在看来还是多虑了，可能是一些同龄人（或是青春期的人）才会对此比较敏感。有时如果不提前明晰一些表述，可能就会有比较偏激的人来说这是性别刻板印象什么什么的，然后越解释越乱，甚至可能变成“哎呀你怎么搞性别歧视！”之类的。我自己是没经历过，但旁观过一些此类情形。

**Comment by xdpwjj** [comment]
佩服小麦能够精准记忆并表达心理活动的能力

**Comment by tsingyu42** [comment]
@xdpwjj > 佩服小麦能够精准记忆并表达心理活动的能力

每次思考留下一道痕迹，痕迹重复多了就变成了记忆刻印。
